version: '3'

services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "2831:2831"
      depends_on:
        - redis
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      command: ["redis-server", "--bind", "redis", "--port", "6379"]
  

  
      